# Generated by Django 4.2.15 on 2024-08-21 13:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='todo',
            old_name='task',
            new_name='task_desc',
        ),
    ]
